export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const USER_REGISTERED_FOR_CONFIRMATION =
  "USER_REGISTERED_FOR_CONFIRMATION";
export const USER_CONFIRMED = "USER_CONFIRMED";
export const LOADING_CONFIRMATION = "LOADING_CONFIRMATION";
export const CONFIRMATION_LOADED = "CONFIRMATION_LOADED";

export const LOADING_RESET = "LOADING_RESET";
export const RESET_LOADED = "RESET_LOADED";
export const RESET_CONFIRMED = "RESET_CONFIRMED";
export const RESET_DONE = "RESET_DONE";

export const SENT_FORGOT_EMAIL = "SENT_FORGOT_EMAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const INIT_PORTFOLIO = "INIT_PORTFOLIO";
export const ADD_UPDATE_ASSET = "ADD_UPDATE_ASSET";
export const GET_PORTFOLIO = "GET_PORTFOLIO";
export const PORTFOLIO_LOADING = "PORTFOLIO_LOADING";
export const PORTFOLIO_LOADED = "PORTFOLIO_LOADED";
export const SET_TICKERS = "SET_TICKERS";
export const CHANGE_SIDE_MENU_ITEM = "CHANGE_SIDE_MENU_ITEM";
export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const GQL_LOADING = "GQL_LOADING";
export const GQL_LOADED = "GQL_LOADED";
export const GET_RECORDS = "GET_RECORDS";
export const GET_CHANGE = "GET_CHANGE";
